apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-fxefddxk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-fxefddxk:c9652ce91b399a67e07682e7b960844d43e1b4ca@sha256:d020703e2cadf59e48265f6ca013771f2432d0720aa566dddf64dddc668cf2d3
        name: container-image  
